import type { Citizen } from "./types";

export const citizens: Citizen[] = [
  {
    slug: "ayush",
    name: "Ayush",
    title: "Chief Technology Officer of Civilization Preservation",
    ministry: "Office of the Architect",
    status: "Founding Citizen",
    statusTone: "founding",
    partyDebt: "₹0 (allegedly self-cleared)",
    photo: 12,
    motto: "One more game and then we'll leave.",
    bio: "Ayush is the principal architect of the Republic's digital infrastructure and the author of roughly 80% of Tippa's surviving lore. He is also dangerously obsessed with pickleball — the State has, on multiple occasions, watched a national emergency wait politely while he finished a match. He believes friendship is a distributed system that occasionally requires a hard restart, ideally after court hours.",
    achievements: [
      "Built the first national archive before anyone asked for one",
      "Declared pickleball the official national sport (sole vote, passed unanimously)",
      "Migrated all of Tippa's memories from a fragile group chat to permanent record",
    ],
    crimes: [
      "Scheduled a constitutional review around a pickleball booking",
      "Said 'one more game' eleven games ago",
      "Once said 'let's circle back' to a birthday",
    ],
    quotes: [
      "We are not a group chat. We are a microservice for joy.",
      "I can't, I have a court booked.",
      "Every party is just a deployment with snacks.",
    ],
    contributions: [
      "Drafted Articles I through VII of the National Constitution",
      "Founded the Tippa Pickleball League (Season Zero, ongoing)",
      "Established the Office of Permanent Record",
    ],
    recent: [
      { date: "Founding Day", text: "Shipped the Republic to production, then booked a court." },
      { date: "This Week", text: "Won a match, told the entire Republic about it." },
      { date: "Last Month", text: "Promised a feature. Filed it under 'after pickleball.'" },
    ],
  },
  {
    slug: "aman",
    name: "Aman",
    nickname: "Unc",
    title: "Minister of Public Communications and National Hospitality",
    ministry: "Ministry of Public Communications",
    status: "Founding Citizen",
    statusTone: "founding",
    partyDebt: "₹1,200 (covered it, will mention it forever)",
    photo: 33,
    motto: "My place. I'll host. Just bring yourselves.",
    bio: "Affectionately known across the Republic as 'Unc,' Aman is the elder statesman energy Tippa never knew it needed — moustache included. He is the nation's host-in-chief: no gathering feels official until it happens at his place, under his roof, with him insisting nobody lift a finger. Every proclamation and every plan flows through him, usually accompanied by an invitation.",
    achievements: [
      "Hosted more national gatherings than any citizen in history",
      "Grew the most distinguished moustache in the Republic",
      "Authored every official proclamation in national history",
    ],
    crimes: [
      "Announced an event before confirming it existed",
      "Insisted on hosting, then made everyone clean up 'their own mess'",
      "Used 'URGENT' for a dinner poll",
    ],
    quotes: [
      "Come over, we'll figure out the food here.",
      "I'll draft a statement.",
      "Beta, sit. I'll handle it.",
    ],
    contributions: [
      "Designated his home a National Gathering Site",
      "Designed the national memo format",
      "Established the daily briefing tradition",
    ],
    recent: [
      { date: "Today", text: "Offered to host something that had no occasion." },
      { date: "Yesterday", text: "Stroked the moustache, announced an announcement." },
      { date: "Last Week", text: "Hosted everyone, refused all help, then sighed loudly." },
    ],
  },
  {
    slug: "ravi",
    name: "Ravi",
    nickname: "Takla Ravi",
    title: "Minister of Compliance, Logistics and Manager Approvals",
    ministry: "Ministry of Sports and Logistics",
    status: "Senior Citizen",
    statusTone: "senior",
    partyDebt: "₹3,400 pending after standup",
    photo: 53,
    motto: "I'd love to, but I'm stuck at Commenda.",
    bio: "Known nationwide as 'Takla Ravi,' he is the Republic's most overworked citizen, permanently chained to his desk at Commenda. He has no time. He has never had time. And yet — the entire Republic has noticed — he somehow always finds a free Sunday to attend pottery workshops with his partner Smruti. The State considers this the single greatest unsolved mystery in national history.",
    achievements: [
      "Survived another quarter at Commenda without disappearing entirely",
      "Attended every couples' pottery workshop while 'having no time' for anyone else",
      "Introduced the concept of 'approval, pending approval'",
    ],
    crimes: [
      "Said he was too busy for the Republic, then spent the weekend making bowls with Smruti",
      "Said 'I'll join in 10 minutes' for two hours",
      "Joined a call from the party so he could leave the party",
    ],
    quotes: [
      "Bro I'm so busy you have no idea.",
      "No it's not a date, it's a pottery workshop.",
      "Let me just finish this one thing.",
    ],
    contributions: [
      "Built the national approvals workflow",
      "Donated 12 suspiciously couple-made mugs to the State",
      "Defined what it means to be perpetually unavailable (except for pottery)",
    ],
    recent: [
      { date: "Today", text: "Was 'in a meeting' during a national holiday." },
      { date: "This Week", text: "Skipped a plan for work, was spotted at a pottery class with Smruti." },
      { date: "Last Month", text: "Promised to come, then Commenda happened." },
    ],
  },
  {
    slug: "smruti",
    name: "Smruti",
    title: "Minister of Nutritional Austerity",
    ministry: "Ministry of Food Security",
    status: "Senior Citizen",
    statusTone: "senior",
    partyDebt: "₹0 (refuses to spend on dessert)",
    photo: 44,
    motto: "No sugar, no salt, no exceptions.",
    bio: "Partner of Senior Citizen Ravi and the Republic's strictest dietary authority, Smruti observes a no-sugar, no-salt regime so devout it has its own national observance. She carries herself with the quiet confidence of a competitive bodybuilder, a claim the State has neither verified nor dared to question. She is also the prime suspect in luring Ravi to weekend pottery workshops.",
    achievements: [
      "Maintained the no-sugar, no-salt doctrine through every festival",
      "Convinced the Republic she could deadlift any of them",
      "Single-handedly prevented seven over-orders",
    ],
    crimes: [
      "Judged everyone's plate while claiming not to",
      "Said 'I'm not that hungry' then finished the fries",
      "Booked yet another pottery workshop and took Ravi hostage",
    ],
    quotes: [
      "Is this air-fried or actually fried?",
      "I'm on a cut.",
      "We're just going for the pottery, relax.",
    ],
    contributions: [
      "Founded the Ministry of Food Security",
      "Wrote the National Clean-Eating Guidelines",
      "Keeps Ravi alive, fed, and gently crafting bowls",
    ],
    recent: [
      { date: "Today", text: "Inspected a menu for hidden sugar like a customs officer." },
      { date: "Yesterday", text: "Did 'one set' in front of everyone, claimed it was leg day." },
      { date: "Last Week", text: "Dragged Ravi to a pottery class instead of the group plan." },
    ],
  },
  {
    slug: "madan",
    name: "Madan",
    nickname: "Black",
    title: "Minister of Delusion and Unverified Confidence",
    ministry: "Ministry of Public Communications",
    status: "Under Internal Review",
    statusTone: "watch",
    partyDebt: "₹6,800 (disputed, confidently)",
    photo: 60,
    motto: "Yeah I'll definitely come this time.",
    bio: "Known throughout the Republic as 'Black,' Madan is the most delusional man in Tippa and its most reliable source of cancelled plans. He confirms attendance with total conviction and appears at roughly none of it. He is trolled relentlessly, takes it with a confidence entirely unsupported by evidence, and remains, against all odds, beloved.",
    achievements: [
      "Confirmed attendance to 14 events. Attended approximately zero.",
      "Withstood more national trolling than any citizen and never flinched",
      "Predicted things confidently; was right about one of them",
    ],
    crimes: [
      "Cancelled at the exact moment everyone arrived",
      "Said 'I'm on the way' from his bed",
      "Ghosted a plan he personally organized",
    ],
    quotes: [
      "Bro I swear I'm coming.",
      "I had a feeling that would happen.",
      "No no, this time for sure.",
    ],
    contributions: [
      "Keeps national morale dangerously high",
      "Is the reason the Republic has a Public Embarrassment Archive",
      "Provides 90% of the group's inside jokes by simply existing",
    ],
    recent: [
      { date: "Today", text: "Confirmed he's coming. The Republic laughed knowingly." },
      { date: "This Week", text: "Cancelled, was trolled, somehow won the argument in his head." },
      { date: "Last Month", text: "Was almost seen in person. Sketches are inconclusive." },
    ],
  },
  {
    slug: "mukesh",
    name: "Mukesh",
    title: "Minister of Finance, Crypto and Payment Parties",
    ministry: "Ministry of Finance",
    status: "Inactive Citizen",
    statusTone: "inactive",
    partyDebt: "Creditor, not debtor (he reminds everyone)",
    photo: 14,
    motto: "It's not spending, it's diversifying.",
    bio: "One of the two richest citizens of the Republic, Mukesh manages both the national treasury and an ever-shifting crypto portfolio he is always 'up' on. He maintains a strict and well-documented preference for women who, in his words, 'look Northeastern' — high cheekbones, sharp features, the full aesthetic. He will explain this at length. He will also, without hesitation, declare that he hates China. The Republic has noted the contradiction, filed it under 'Ministerial Logic,' and moved on. His wealth funds the parties; his ledger ensures everyone pays him back anyway.",
    achievements: [
      "Held the line on a crypto bag through three national heart attacks",
      "Recovered debts thought permanently lost",
      "Successfully identified 'Northeastern energy' in three separate introductions at one party",
      "Vetoed a group trip to China while approving a weekend in Gangtok",
    ],
    crimes: [
      "Explained 'the dip' to people who did not ask",
      "Added interest 'as a joke' (it was not a joke)",
      "Said 'trust me, it'll bounce back' about everything",
      "Ordered from a restaurant with a suspiciously Chinese name, then sent it back citing 'principles'",
      "Described someone's face as 'very Northeastern' in a voice note the Republic still has on file",
    ],
    quotes: [
      "We're early, trust me.",
      "Sending the split now.",
      "It's not about the money, it's about the principle.",
      "Bro she has that Northeastern look, you know what I mean.",
      "I hate China. No, I don't want to talk about it. Yes, I know where Gangtok is.",
      "It's different. The face is Northeastern. The country is — no.",
    ],
    contributions: [
      "Built the National Treasury and the ledger",
      "Authored Tippa's debt recovery doctrine",
      "Co-founded the upcoming TippaSplit platform",
      "Established the Republic's unofficial 'Geographic Preference' policy (rejected unanimously)",
    ],
    recent: [
      { date: "Today", text: "Checked the charts 40 times, declared himself 'up'." },
      { date: "Yesterday", text: "Followed up on a 2-month-old ₹120." },
      { date: "This Week", text: "Rejected a Chinese restaurant for the group dinner. Suggested Northeastern instead. Nobody asked for either." },
      { date: "Last Week", text: "Balanced the books. Was emotional about it." },
    ],
  },
  {
    slug: "mohsin",
    name: "Mohsin",
    nickname: "Mastikhor Mohsin",
    title: "Minister of Foreign Affairs and Visa Acquisition",
    ministry: "Ministry of Foreign Affairs",
    status: "Active Citizen",
    statusTone: "active",
    partyDebt: "₹2,100 in airport snacks",
    photo: 11,
    motto: "Let me just talk to that guy real quick.",
    bio: "'Mastikhor Mohsin' is the Republic's diplomat, charmer, and chronic visa-applicant. He can befriend any foreigner within a single conversation and treats visa applications less as paperwork and more as a beloved hobby. Wherever there is a tourist, an embassy queue, or a passport to be stamped, Mohsin is already mid-conversation.",
    achievements: [
      "Befriended foreigners on three continents without leaving the chat",
      "Applied for visas purely for the joy of applying",
      "Negotiated three group trips into existence",
    ],
    crimes: [
      "Started a 40-minute chat with a stranger 'to practice'",
      "Planned an itinerary nobody followed",
      "Lost a boarding pass with great confidence",
    ],
    quotes: [
      "Bro this guy's from Spain, one sec.",
      "I have a contact there.",
      "Let me just apply, you never know.",
    ],
    contributions: [
      "Established Tippa's foreign trip doctrine",
      "Built the national contacts network",
      "Maintains diplomatic ties with five other friend groups",
    ],
    recent: [
      { date: "Today", text: "Applied for a visa to a country with no plans to visit." },
      { date: "This Week", text: "Made a foreign friend at a café in eight minutes." },
      { date: "Last Month", text: "Got everyone a visa appointment somehow." },
    ],
  },
  {
    slug: "ujjwal",
    name: "Ujjwal",
    nickname: "Darual",
    title: "Keeper of Strategic Beer Reserves",
    ministry: "Ministry of Food Security",
    status: "Active Citizen",
    statusTone: "active",
    partyDebt: "₹0 (settled in kind)",
    photo: 8,
    motto: "The reserves must never run dry.",
    bio: "Known to all as 'Darual,' Ujjwal is never not holding a beer. He is the living embodiment of the Strategic Reserve and the most dependable man at any gathering — he knows what's in the fridge, what's been promised, and what's been quietly consumed. No celebration in Tippa has ever failed due to a shortage on his watch.",
    achievements: [
      "Maintained 100% reserve availability across all parties",
      "Has never, in recorded history, arrived empty-handed",
      "Predicted every shortage before it occurred",
    ],
    crimes: [
      "Dipped into the strategic reserve 'for testing'",
      "Declared a Tuesday a 'national occasion'",
      "Counted the same crate twice (optimistically)",
    ],
    quotes: [
      "One more round, for the Republic.",
      "I've got it covered.",
      "We have exactly enough. Trust me.",
    ],
    contributions: [
      "Founded the Strategic Beer Reserve",
      "Authored the National Celebration Readiness plan",
      "Personally stocked every founding event",
    ],
    recent: [
      { date: "Today", text: "Audited the reserves. They passed (barely)." },
      { date: "Yesterday", text: "Restocked before anyone noticed the gap." },
      { date: "Last Week", text: "Declared an impromptu national holiday." },
    ],
  },
  {
    slug: "mayank",
    name: "Mayank",
    nickname: "Montu Mayank",
    title: "Minister of Drip and Underground Frequencies",
    ministry: "Ministry of Public Communications",
    status: "Active Citizen",
    statusTone: "active",
    partyDebt: "₹1,500 in concert tickets owed",
    photo: 15,
    motto: "You haven't heard this artist, trust me.",
    bio: "'Montu Mayank' is the Republic's resident rap connoisseur and undisputed drip authority. He moves exclusively in baggy fits and underground tracks nobody else has heard yet. His taste is three months ahead of everyone, a gap he is happy to remind the nation about regularly. Half of Tippa's playlist is just Mayank's recommendations on delay.",
    achievements: [
      "Introduced the Republic to 41 artists before they were cool",
      "Set the national standard for baggy, effortless drip",
      "Curated the underground soundtrack to every late night",
    ],
    crimes: [
      "Said 'this is so underground' about a chart-topping song",
      "Skipped a track everyone was enjoying for 'a better one'",
      "Described an outfit as 'just something I threw on' (it took an hour)",
    ],
    quotes: [
      "Nah this guy's still underground.",
      "Wait, listen to this verse.",
      "It's not baggy, it's the silhouette.",
    ],
    contributions: [
      "Built the National Underground Playlist Archive",
      "Defined the official national dress code: baggy",
      "Soundtracked every national celebration with deep cuts",
    ],
    recent: [
      { date: "Today", text: "Sent the group a track captioned 'before they blow up'." },
      { date: "Yesterday", text: "Showed up in the baggiest fit the Republic had ever seen." },
      { date: "Last Week", text: "Argued an artist was underground. They had a Grammy." },
    ],
  },
  {
    slug: "parth",
    name: "Parth",
    title: "Minister of Spiritual Attendance and Remote Presence",
    ministry: "Ministry of Finance",
    status: "Active Citizen",
    statusTone: "active",
    partyDebt: "₹0 (paid remotely, in full)",
    photo: 51,
    motto: "I'm there in spirit, always.",
    bio: "One of the two richest citizens of the Republic, Parth is rarely present in body but eternally present in spirit. He funds, blesses, and approves of nearly everything from afar. His physical attendance is so rare it is commemorated; his moral and financial support is so constant it is taken for granted. The Republic considers him a permanent silent partner.",
    achievements: [
      "Achieved 100% spiritual attendance despite minimal physical presence",
      "Quietly funded gatherings he could not attend",
      "Became a legend by simply being unavailable and generous",
    ],
    crimes: [
      "RSVP'd 'maybe' to his own celebration",
      "Was 'definitely coming' from another city",
      "Sent money instead of showing up, then was thanked anyway",
    ],
    quotes: [
      "Enjoy, it's on me.",
      "I'll try to make it.",
      "I'm with you guys, you know that.",
    ],
    contributions: [
      "Endowed the Republic's celebration fund",
      "Set the gold standard for generous absence",
      "Proved presence is a state of mind",
    ],
    recent: [
      { date: "Today", text: "Was present in spirit. Spirit was very supportive." },
      { date: "This Week", text: "Paid for a round he was not physically at." },
      { date: "Last Month", text: "Appeared in person. The event was declared historic." },
    ],
  },
  {
    slug: "parul",
    name: "Parul",
    title: "Minister of Group Photos and Memory Preservation",
    ministry: "Ministry of Public Communications",
    status: "Active Citizen",
    statusTone: "active",
    partyDebt: "₹600 in photo prints never collected",
    photo: 47,
    motto: "One more, someone blinked.",
    bio: "Partner of Founding Citizen Aman and co-keeper of the National Gathering Site, Parul ensures no national moment goes undocumented. While others live the memory, she preserves it. Together she and Aman form the Republic's first family of hospitality — he hosts the gathering, she makes sure there's photographic proof it happened.",
    achievements: [
      "Archived every group photo in national history",
      "Co-hosts the Republic's most important gatherings",
      "Caught the candid that became Tippa's first national portrait",
    ],
    crimes: [
      "Took 47 photos to get 'the one'",
      "Said 'last one' four group photos ago",
      "Posted the photo nobody approved",
    ],
    quotes: [
      "Everyone get in, get in!",
      "One more, just in case.",
      "I'll send them in the group... eventually.",
    ],
    contributions: [
      "Founded the National Photo Archive",
      "Established the mandatory group photo tradition",
      "Preserved the Republic's entire visual memory",
    ],
    recent: [
      { date: "Today", text: "Organized 3,000 photos into one folder." },
      { date: "Yesterday", text: "Promised to send the photos 'tonight.'" },
      { date: "Last Week", text: "Took the official Founding Day portrait." },
    ],
  },
  {
    slug: "sehaj",
    name: "Sehaj",
    title: "Minister of Fragrance, Gains and Cardio Avoidance",
    ministry: "Ministry of Foreign Affairs",
    status: "Active Citizen",
    statusTone: "active",
    partyDebt: "₹4,500 in perfume (worth it, he says)",
    photo: 26,
    motto: "Smell good, lift heavy, never run.",
    bio: "Sehaj is the best-smelling citizen in the Republic and its most devoted gym-goer — provided no cardio is involved. He invests in expensive fragrances the way others invest in property, and he will lift any weight you ask, as long as the treadmill stays off. His one unconquered frontier remains, with great national sympathy, the dating scene.",
    achievements: [
      "Owns a fragrance collection valued as a national asset",
      "Never skipped a lift, never completed a run",
      "Made the entire Republic smell better by proximity",
    ],
    crimes: [
      "Called a 5-minute walk 'too much cardio'",
      "Spent rent money on a single bottle of perfume",
      "Asked the gym mirror for advice it could not give",
    ],
    quotes: [
      "This one's an oud, you wouldn't get it.",
      "Cardio kills your gains.",
      "I'm great with everyone except the one I like.",
    ],
    contributions: [
      "Established the National Fragrance Standard",
      "Built the Republic's only respectable lifting program",
      "Provides the group its most relatable struggles",
    ],
    recent: [
      { date: "Today", text: "Bought a perfume that costs more than the party." },
      { date: "Yesterday", text: "Hit a PR on the bench, refused the treadmill." },
      { date: "Last Week", text: "Wrote a perfect text, never sent it." },
    ],
  },
];

export function getCitizen(slug: string) {
  return citizens.find((c) => c.slug === slug);
}
